language: php
sudo: false
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "7.1" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - cd app
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer update $COMPOSER_FLAGS
matrix:
  include:
    - php: 7.2
      script: vendor/bin/simple-phpunit
      before_script:
        - mkdir -p build/logs
      after_script:
        - travis_retry php vendor/bin/php-coveralls -v
  fast_finish: true
