language: php
sudo: false
services:
  - rabbitmq
  - redis-server
before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - cd app
before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install $COMPOSER_FLAGS --ignore-platform-reqs
matrix:
  include:
    - php: 7.3
      script: bin/phpunit
      before_script:
        - mkdir -p build/logs
      after_script:
        - travis_retry php vendor/bin/php-coveralls -v
  fast_finish: true
