language: php
sudo: false
services:
  - rabbitmq
  - redis-server
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "7.1" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - cd app
  - printf "\n" | pecl install amqp
install:
  - composer update $COMPOSER_FLAGS
matrix:
  include:
    - php: 7.3
      script: vendor/bin/simple-phpunit
      before_script:
        - mkdir -p build/logs
      after_script:
        - travis_retry php vendor/bin/php-coveralls -v
  fast_finish: true
