version: '3'
services:
    web:
      image: nginx
      links:
        - app
      depends_on:
        - app
      volumes:
        - "./app:/var/www/app"
        - "./.docker/config/nginx/vhost/sf4_vhost:/etc/nginx/conf.d/default.conf:ro"
        - "./media:/media"
    app:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - mariadb
        - redis
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      env_file:
        - .env
    video_processor:
      build: .
      deploy:
        mode: global
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - redis
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      env_file:
        - .env
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "scan_file"
        - "-vvv"
    check_video:
      build: ../php-consumer-checkvideo
      links:
        - rabbitmq
      depends_on:
        - app
        - rabbitmq
      volumes:
        - "./media:/media"
      env_file:
        - .env
      restart: always
    process_file:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - redis
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      env_file:
        - .env
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "process_file"
        - "-vvv"
    get_video_metadata:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - redis
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      env_file:
        - .env
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "get_video_metadata"
        - "-vvv"
    consumer_thumbnail:
      image: pbxg33k/consumer-php-thumbnails
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - redis
        - mariadb
        - rabbitmq
      volumes:
        - "./media:/media"
      env_file:
        - .env
      restart: always
      environment:
        MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/generate_thumbnail

    mariadb:
      image: mariadb
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        - "MYSQL_ROOT_PASSWORD=rootPass"
        - "MYSQL_USER=appuser"
        - "MYSQL_PASSWORD=userPass"
        - "MYSQL_DATABASE=app"

    rabbitmq:
      image: rabbitmq:management-alpine

    redis:
      image: redis
