version: '3'
services:
    web:
      image: nginx
      links:
        - app
      depends_on:
        - app
      volumes:
        - "./app:/var/www/app"
        - "./.docker/config/nginx/vhost/sf4_vhost:/etc/nginx/conf.d/default.conf:ro"
        - "./media:/media"
    app:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      env_file:
        - .env
    video_processor:
      build: .
      deploy:
        mode: global
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      env_file:
        - .env
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "scan_file"
        - "-vvv"
    check_video:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      environment:
        - APP_ENV=dev
        - APP_DEBUG=1
        - APP_SECRET=83512d52ee8797e6e9de2322dc781885
        - DATABASE_URL=//appuser:userPass@mariadb:3306/app
        - MT_CONF_FILE=/var/www/app/config/mt.json
        - MEDIA_DIR=/media
        - THUMB_DIR=/media/thumbs
        - ENQUEUE_DSN=amqp://guest:guest@rabbitmq:5672
        - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672/%2f/
        - REDIS_URI=redis://redis
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "check_video"
        - "-vvv"
    process_file:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      environment:
        - APP_ENV=dev
        - APP_DEBUG=1
        - APP_SECRET=83512d52ee8797e6e9de2322dc781885
        - DATABASE_URL=//appuser:userPass@mariadb:3306/app
        - MT_CONF_FILE=/var/www/app/config/mt.json
        - MEDIA_DIR=/media
        - THUMB_DIR=/media/thumbs
        - ENQUEUE_DSN=amqp://guest:guest@rabbitmq:5672
        - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672/%2f/
        - REDIS_URI=redis://redis
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "process_file"
        - "-vvv"
    get_video_metadata:
      build: .
      links:
        - mariadb
        - rabbitmq
      depends_on:
        - app
        - mariadb
        - rabbitmq
      volumes:
        - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./app:/var/www/app"
        - "./media:/media"
      environment:
        - APP_ENV=dev
        - APP_DEBUG=1
        - APP_SECRET=83512d52ee8797e6e9de2322dc781885
        - DATABASE_URL=//appuser:userPass@mariadb:3306/app
        - MT_CONF_FILE=/var/www/app/config/mt.json
        - MEDIA_DIR=/media
        - THUMB_DIR=/media/thumbs
        - ENQUEUE_DSN=amqp://guest:guest@rabbitmq:5672
        - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672/%2f/
        - REDIS_URI=redis://redis
      restart: always
      command:
        - "/var/www/app/bin/console"
        - "messenger:consume"
        - "get_video_metadata"
        - "-vvv"

    mariadb:
      image: mariadb
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        - "MYSQL_ROOT_PASSWORD=rootPass"
        - "MYSQL_USER=appuser"
        - "MYSQL_PASSWORD=userPass"
        - "MYSQL_DATABASE=app"

    rabbitmq:
      image: rabbitmq:management-alpine

    redis:
      image: redis
