<?php
namespace App\Tests\Service;

use App\Event\DirectoryFoundEvent;
use App\Event\FileFoundEvent;
use App\Event\QualifiedVideoFileFound;
use App\Event\VideoFileFoundEvent;
use App\Service\FileScanService;
use App\Service\JAVProcessorService;
use org\bovigo\vfs\content\LargeFileContent;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class FileScanServiceTest extends TestCase
{
    /**
     * @var vfsStreamDirectory
     */
    private $rootFs;

    /**
     * @var MockObject|LoggerInterface
     */
    private $logger;

    /**
     * @var MockObject|EventDispatcherInterface
     */
    private $eventDispatcher;

    /**
     * @var MockObject|JAVProcessorService
     */
    private $javProcessorService;

    /**
     * @var FileScanService
     */
    private $fileScanService;

    protected function setUp()
    {
        $this->logger               = $this->createMock(LoggerInterface::class);
        $this->eventDispatcher      = $this->createMock(EventDispatcherInterface::class);
        $this->javProcessorService  = $this->createMock(JAVProcessorService::class);
        $this->fileScanService      = new FileScanService(
            $this->logger,
            $this->eventDispatcher,
            $this->javProcessorService
        );

        $this->rootFs = vfsStream::setup('testDir');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function willFindFile()
    {
        // Mock file which will be processed
        vfsStream::newFile('ABC-123.mkv')
            ->withContent(new LargeFileContent(500000000))
            ->at($this->rootFs);

        // Mock file which will be ignored (too small)
        vfsStream::newFile('ABC-124.mp4')
            ->withContent(LargeFileContent::withMegabytes(5))
            ->at($this->rootFs);

        $this->eventDispatcher->expects($this->exactly(7))
            ->method('dispatch')
            ->withConsecutive(
                [$this->equalTo(DirectoryFoundEvent::NAME), $this->isInstanceOf(DirectoryFoundEvent::class)],
                [$this->equalTo(DirectoryFoundEvent::NAME), $this->isInstanceOf(DirectoryFoundEvent::class)],
                [$this->equalTo(FileFoundEvent::NAME), $this->isInstanceOf(FileFoundEvent::class)],
                [$this->equalTo(VideoFileFoundEvent::NAME), $this->isInstanceOf(VideoFileFoundEvent::class)],
                [$this->equalTo(QualifiedVideoFileFound::NAME), $this->isInstanceOf(QualifiedVideoFileFound::class)],
                [$this->equalTo(FileFoundEvent::NAME), $this->isInstanceOf(FileFoundEvent::class)],
                [$this->equalTo(VideoFileFoundEvent::NAME), $this->isInstanceOf(VideoFileFoundEvent::class)]
            );

        $this->javProcessorService->expects($this->once())
            ->method('filenameContainsID')
            ->willReturn(true);

        $this->fileScanService->scanDir($this->rootFs->url());

        $this->assertInstanceOf(\SplFileInfo::class, $this->fileScanService->getFiles()->first());
    }

    /**
     * @test
     */
    public function willLogErrorIfExceptionIsThrownByJavProcessorService()
    {
        // Mock file which will be processed
        vfsStream::newFile('ABC-123.mkv')
            ->withContent(new LargeFileContent(500000000))
            ->at($this->rootFs);

        $this->eventDispatcher->expects($this->exactly(4))
            ->method('dispatch')
            ->withConsecutive(
                [$this->equalTo(DirectoryFoundEvent::NAME), $this->isInstanceOf(DirectoryFoundEvent::class)],
                [$this->equalTo(DirectoryFoundEvent::NAME), $this->isInstanceOf(DirectoryFoundEvent::class)],
                [$this->equalTo(FileFoundEvent::NAME), $this->isInstanceOf(FileFoundEvent::class)],
                [$this->equalTo(VideoFileFoundEvent::NAME), $this->isInstanceOf(VideoFileFoundEvent::class)]
            );

        $this->javProcessorService->expects($this->once())
            ->method('filenameContainsID')
            ->willThrowException(new \Exception("Exception message"));

        $this->logger->expects($this->once())
            ->method('error');

        $this->fileScanService->scanDir($this->rootFs->url());
    }
}
