<?php
namespace App\Tests\Service;

use App\Entity\JavFile;
use App\Entity\Title;
use App\Service\JAVProcessorService;
use Doctrine\ORM\EntityManagerInterface;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Finder\SplFileInfo;

class JAVProcessorServiceTest extends TestCase
{
    protected $logger;

    protected $dispatcher;

    protected $entityManager;

    /**
     * @var JAVProcessorService
     */
    protected $service;

    /**
     * @var vfsStreamDirectory
     */
    private $mediaRoot;

    /**
     * @var vfsStreamDirectory
     */
    private $mediaThumbRoot;

    public function setUp()
    {
        $logger = $this->logger = $this->getMockBuilder(LoggerInterface::class)
            ->getMock();

        $dispatcher = $this->dispatcher = $this->getMockBuilder(EventDispatcherInterface::class)
            ->getMock();

        $entityManager = $this->entityManager = $this->getMockBuilder(EntityManagerInterface::class)
            ->getMock();

        $this->mediaRoot = vfsStream::setup('media');
        $this->mediaThumbRoot = vfsStream::setup('thumb');

        $this->service = new JAVProcessorService($logger,$dispatcher,$entityManager,vfsStream::url('media'),vfsStream::url('thumb'));

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function extractsIDFromFilename()
    {
        $successObj = new Title();
        $filenameVariations = [
            "[ABC-123].mp4",
            "ABC-123.mp4",
            "A fancy title with ID worked in title ABC-123.wmv",
            "ABC-123 kek.mp4",
            "0302abc-123-h264.mp4",
            "[NoDRM]-abc123.mkv",
            "[Thz.la]abc-123.wmv",
            "ABC-123_720p.mp4"
        ];

        $successObj
            ->setCatalognumber('ABC-123');

        foreach($filenameVariations as $filenameVariation) {
            $successObj->addFile((new JavFile())->setFilename($filenameVariation));

            $processedFilenameResult = JAVProcessorService::extractIDFromFilename($successObj->getFiles()->first()->getFilename());

            $this->assertSame($successObj->getCatalognumber(), $processedFilenameResult->getCatalognumber());

            $this->assertSame(
                $successObj->getFiles()->first()->getFilename(),
                $processedFilenameResult->getFiles()->first()->getFilename());
        }

    }
}
