framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            amqp: '%env(RABBITMQ_SERVER)%default'
            check_video: '%env(RABBITMQ_SERVER)%check_video'
            generate_thumbnail: '%env(RABBITMQ_SERVER)%generate_thumbnail'
            get_video_metadata: '%env(RABBITMQ_SERVER)%get_video_metadata'
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
            'Pbxg33k\MessagePack\Message\CheckVideoMessage': check_video
            'Pbxg33k\MessagePack\Message\GenerateThumbnailMessage': generate_thumbnail
            'Pbxg33k\MessagePack\Message\GetVideoMetadataMessage': get_video_metadata
            'Pbxg33k\MessagePack\Message\ProcessFileMessage': amqp
            '*': amqp
